### PR TITLE
fabfile.py: fix the sequence of importing GS layers

### PR DESCRIPTION
**Pull request by daniviga**
This fixes an issue about keywords and metadata.

With the previous behavior GS was synchronizing with an empty GN: this was causing all the keywords to disappear in GS.

Now the sequence is:
- Load the fixture in the GN database
- Push the GS data
- Synchronize GS data with GN

Unblock https://github.com/gem/oq-platform/pull/449
Tests https://ci.openquake.org/job/zdevel_oq-platform/76/

### CODE REVIEW

**Comment by ptormene** [comment]
The test is red :(

**Comment by daniviga** [comment]
Should be fixed here: https://ci.openquake.org/job/zdevel_oq-platform/79/

There's a circular dependency: you must have run `updatelayers` before pushing the fixtures, but then you have to run it again to synchronize GS with the GN metadata (and keywords).

This will slow down the installation, but I don't have any other idea on how to fix it.

**Comment by daniviga** [comment]
Test are now green: https://ci.openquake.org/job/zdevel_oq-platform/79/

**Comment by ptormene** [comment]
LGTM

**Pull request merged**
