### PR TITLE
exposure/util.py: close forcefully cursor connection

### PR DESCRIPTION
**Pull request by daniviga**
This should fix (or at least mitigate) https://bugs.launchpad.net/oq-platform/+bug/1472139

### CODE REVIEW

**Comment by pslh** [comment]
Tested on staging for Slovenia (NERA) and Mexico (UN Habitat L1) - all seems to be working.

**Comment by pslh** [comment]
Also tested fraction download and bounding-box grid download.  All working as expected.
LGTM

**Comment by micheles** [comment]
LGTM from me too.

**Comment by daniviga** [comment]
Thanks all. Merged.

**Comment by daniviga** [comment]
Since the deployment of 1.2.0 is still TBA and some work on GED is undergoing in these days I backported this patch into 1.1.0.

**Pull request merged**
